# user-build 用户模块的构建流程，必须通过构建和测试，才能合并到主分支
name: user-build

on:
  push:
    paths:
      - "user/**" # 只在user目录有变更时触发
  pull_request:
    paths:
      - "user/**" # 只在user目录有变更时触发

jobs:
  build-user-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20" # 使用合适的Go版本

      - name: Build user module
        run: |
          cd user
          go build -v ./main.go
