name: User Module Workflow

on:
  push:
    paths:
      - "user/**" # 只在user目录有变更时触发
  pull_request:
    paths:
      - "user/**" # 只在user目录有变更时触发
  release:
    types:
      - published  # 当发布新的 release 时触发

jobs:
  build-user-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('user/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24" # 使用合适的Go版本

      - name: Tidy and Build user module
        working-directory: user
        run: |
          go mod tidy
          go build -v ./user.go

      - name: Run tests
        working-directory: user
        run: |
          go test -v ./...

  build-and-push-image:
    needs: build-user-module
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tag
        id: determine_tag
        run: |
          echo "TAG=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./user
          file: ./user/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/another-mentor-user:latest
            ghcr.io/${{ github.repository_owner }}/another-mentor-user:${{ steps.determine_tag.outputs.TAG }}
